project_id = "sfmgdvjwmoxoeqmcarbv"

[functions.generate-cv]
verify_jwt = false

[functions.generate-anschreiben]
verify_jwt = false

[functions.extract-job]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.parse-cv]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true
